import mods.MTUtils;
MTUtils.setBlockDrops(null, <BiomesOPlenty:foliage:4>, [<kitchenCraftFoods:veggie:0>], [1.5], [<kitchenCraftFoods:veggie:0>]);
MTUtils.setBlockDrops(null, <BiomesOPlenty:foliage:13>, [<kitchenCraftFoods:veggie:1>], [1.5], [<kitchenCraftFoods:veggie:1>]);
MTUtils.setBlockDrops(null, <BiomesOPlenty:foliage:9>, [<kitchenCraftFoods:veggie:2>], [1.5], [<kitchenCraftFoods:veggie:2>]);
MTUtils.setBlockDrops(null, <BiomesOPlenty:flowers2:4>, [<kitchenCraftFoods:veggie:3>], [1.5], [<kitchenCraftFoods:veggie:3>]);
MTUtils.setBlockDrops(null, <BiomesOPlenty:flowers:1>, [<kitchenCraftFoods:veggie:4>], [1.5], [<BiomesOPlenty:flowers:6>]);
MTUtils.setBlockDrops(null, <BiomesOPlenty:foliage:11>, [<kitchenCraftFoods:veggie:5>], [1.5], [<BiomesOPlenty:foliage:11>]);
MTUtils.setBlockDrops(null, <BiomesOPlenty:flowers:7>, [<kitchenCraftFoods:veggie:6>], [1.5], [<BiomesOPlenty:flowers2:5>]);
MTUtils.setBlockDrops(null, <BiomesOPlenty:foliage:5>, [<kitchenCraftFoods:veggie:7>], [1.5], [<BiomesOPlenty:foliage:5>]);
MTUtils.clearDrops();